# frozen_string_literal: true

# Tracks all invoices generated by WetWijzer for subscriptions and credit purchases.
# Stored in the accounts database alongside users and subscriptions.
class PlatformInvoice < AccountRecord
  FINANCIAL_CONTENT_ATTRIBUTES = %w[
    user_id
    invoice_number
    invoice_type
    subtotal_cents
    vat_cents
    total_cents
    currency
    customer_name
    customer_vat
    customer_email
    customer_address
    customer_country
    invoice_locale
    original_invoice_id
    refund_reason
    payment_provider
    provider_invoice_id
    provider_payment_id
    document_payload
  ].freeze

  # Accounting records outlive an erased account; retained customer fields are
  # governed by the statutory invoice-retention period.
  belongs_to :user, optional: true
  belongs_to :original_invoice, class_name: 'PlatformInvoice', optional: true
  has_one :credit_note, class_name: 'PlatformInvoice', foreign_key: :original_invoice_id
  has_many :credit_notes, class_name: 'PlatformInvoice', foreign_key: :original_invoice_id
  has_many :mollie_payment_adjustments,
           foreign_key: :invoice_id,
           inverse_of: :invoice,
           dependent: :nullify

  TYPES = %w[subscription credit_purchase credit_note chargeback_reversal].freeze
  # 'reserving' = number claimed, PDF not yet generated (see InvoiceService
  # .reserve_invoice!). Terminal states: generated → sent → peppol_sent; failed.
  STATUSES = %w[reserving generated sent peppol_sent failed].freeze
  OCTOPUS_STATUSES = %w[pending synced peppol_sending peppol_sent peppol_delivered failed].freeze
  PREFIX = 'WWIZ'

  validates :invoice_number, presence: true, uniqueness: true
  validates :invoice_type, presence: true, inclusion: { in: TYPES }
  validates :subtotal_cents, :vat_cents, :total_cents, presence: true,
                                                       numericality: { greater_than_or_equal_to: 0 }
  validates :status, presence: true, inclusion: { in: STATUSES }
  validates :customer_country,
            format: { with: /\A[A-Z]{2}\z/ },
            allow_blank: true
  validates :invoice_locale,
            inclusion: { in: %w[nl fr de en] },
            allow_blank: true
  validate :issued_financial_content_is_immutable, on: :update
  before_destroy :prevent_accounting_record_destruction

  # Encrypt customer PII at rest (GDPR Art. 32 - financial data protection)
  encrypts :customer_name
  # deterministic: allows search by email. fixed: false so rotation
  # re-encrypts under the NEWEST key (FBL-011).
  encrypts :customer_email, deterministic: { fixed: false }
  encrypts :customer_vat
  encrypts :customer_address

  scope :for_user, ->(user) { where(user: user).order(created_at: :desc) }
  scope :recent, -> { order(created_at: :desc) }

  # Octopus sync scopes
  scope :needs_octopus_sync, -> { where(octopus_status: [nil]).where(status: 'sent') }

  # Generate the next sequential invoice number: WWIZ-2026-0001
  # Uses database as authoritative source (not filesystem scan)
  def self.next_number(year: nil)
    year ||= Time.current.year
    prefix = "#{PREFIX}-#{year}-"

    last = where('invoice_number LIKE ?', "#{prefix}%")
           .order(invoice_number: :desc)
           .pick(:invoice_number)

    seq = if last
            last.split('-').last.to_i + 1
          else
            1
          end

    "#{prefix}#{seq.to_s.rjust(4, '0')}"
  end

  def subtotal_euros
    subtotal_cents / 100.0
  end

  def vat_euros
    vat_cents / 100.0
  end

  def total_euros
    total_cents / 100.0
  end

  def safe_pdf_path
    safe_document_path(pdf_path, '.pdf')
  end

  def safe_xml_path
    safe_document_path(xml_path, '.xml')
  end

  def pdf_exists?
    safe_pdf_path.present?
  end

  def xml_exists?
    safe_xml_path.present?
  end

  def mark_sent!
    update!(status: 'sent', sent_at: Time.current)
  end

  def mark_peppol_sent!(guid)
    update!(status: 'peppol_sent', peppol_guid: guid, sent_at: Time.current)
  end

  def mark_failed!(reason = nil)
    update!(status: 'failed')
    Rails.logger.error("Invoice #{invoice_number} failed: #{reason}") if reason
  end

  def credit_note?
    invoice_type == 'credit_note'
  end

  def chargeback_reversal?
    invoice_type == 'chargeback_reversal'
  end

  # Generate the next credit note number: WWIZ-CN-2026-0001
  def self.next_credit_note_number(year: nil)
    year ||= Time.current.year
    prefix = "#{PREFIX}-CN-#{year}-"

    last = where('invoice_number LIKE ?', "#{prefix}%")
           .order(invoice_number: :desc)
           .pick(:invoice_number)

    seq = if last
            last.split('-').last.to_i + 1
          else
            1
          end

    "#{prefix}#{seq.to_s.rjust(4, '0')}"
  end

  # --- Octopus status helpers ---

  def octopus_synced?
    %w[synced peppol_sending peppol_sent peppol_delivered].include?(octopus_status)
  end

  def octopus_pending?
    octopus_status == 'pending'
  end

  def octopus_failed?
    octopus_status == 'failed'
  end

  def needs_octopus_sync?
    octopus_status.nil? && status == 'sent'
  end

  def octopus_status_label
    case octopus_status
    when nil then '-'
    when 'pending' then '⏳ Wachten'
    when 'synced' then '✅ Gesynchroniseerd'
    when 'peppol_sending' then '🔄 PEPPOL verzending...'
    when 'peppol_sent' then '🐙 PEPPOL verzonden'
    when 'peppol_delivered' then '📬 PEPPOL afgeleverd'
    when 'failed' then '❌ Mislukt'
    else octopus_status
    end
  end

  private

  # A failed/reserving document may finish its one-way generation transition.
  # Once generated, its number, customer snapshot, commercial content, tax
  # basis, provider link, and amounts are statutory accounting history.
  def issued_financial_content_is_immutable
    previous_status = attribute_in_database('status')
    return if %w[reserving failed].include?(previous_status)

    changed = FINANCIAL_CONTENT_ATTRIBUTES.select do |attribute|
      will_save_change_to_attribute?(attribute)
    end
    return if changed.empty?

    errors.add(:base, 'issued accounting content is immutable')
  end

  def prevent_accounting_record_destruction
    errors.add(:base, 'accounting documents cannot be destroyed; issue a correction instead')
    throw(:abort)
  end

  # Invoice file paths are persisted because the Python generator returns them.
  # Treat those database values as untrusted before any download, attachment, or
  # accounting export: a compromised/stale row must not turn `send_file` or
  # `File.binread` into an arbitrary-file read.
  def safe_document_path(stored_path, expected_extension)
    return if stored_path.blank?

    output_root = Pathname.new(
      ENV.fetch('INVOICE_OUTPUT_DIR') { Rails.root.join('storage', 'invoices').to_s }
    ).expand_path.realpath
    candidate = Pathname.new(stored_path.to_s)
    candidate = Rails.root.join(candidate) unless candidate.absolute?
    candidate = candidate.expand_path.realpath

    return unless candidate.file?
    return unless candidate.extname.casecmp?(expected_extension)
    return unless candidate.to_s.start_with?("#{output_root}#{File::SEPARATOR}")

    candidate.to_s
  rescue Errno::ENOENT, Errno::EACCES, Errno::ENOTDIR
    nil
  end
end
