# frozen_string_literal: true

# Tracks all invoices generated by WetWijzer for subscriptions and credit purchases.
# Stored in the accounts database alongside users and subscriptions.
class PlatformInvoice < AccountRecord
  belongs_to :user
  belongs_to :original_invoice, class_name: 'PlatformInvoice', optional: true
  has_one :credit_note, class_name: 'PlatformInvoice', foreign_key: :original_invoice_id

  TYPES = %w[subscription credit_purchase credit_note].freeze
  STATUSES = %w[generated sent peppol_sent failed].freeze
  OCTOPUS_STATUSES = %w[pending synced peppol_sending peppol_sent peppol_delivered failed].freeze
  PREFIX = 'WWIZ'

  validates :invoice_number, presence: true, uniqueness: true
  validates :invoice_type, presence: true, inclusion: { in: TYPES }
  validates :subtotal_cents, :vat_cents, :total_cents, presence: true,
                                                       numericality: { greater_than_or_equal_to: 0 }
  validates :status, presence: true, inclusion: { in: STATUSES }

  # Encrypt customer PII at rest (GDPR Art. 32 - financial data protection)
  encrypts :customer_name
  encrypts :customer_email, deterministic: true # deterministic: allows search by email
  encrypts :customer_vat
  encrypts :customer_address

  scope :for_user, ->(user) { where(user: user).order(created_at: :desc) }
  scope :recent, -> { order(created_at: :desc) }

  # Octopus sync scopes
  scope :needs_octopus_sync, -> { where(octopus_status: [nil]).where(status: 'sent') }

  # Generate the next sequential invoice number: WWIZ-2026-0001
  # Uses database as authoritative source (not filesystem scan)
  def self.next_number(year: nil)
    year ||= Time.current.year
    prefix = "#{PREFIX}-#{year}-"

    last = where('invoice_number LIKE ?', "#{prefix}%")
           .order(invoice_number: :desc)
           .pick(:invoice_number)

    seq = if last
            last.split('-').last.to_i + 1
          else
            1
          end

    "#{prefix}#{seq.to_s.rjust(4, '0')}"
  end

  def subtotal_euros
    subtotal_cents / 100.0
  end

  def vat_euros
    vat_cents / 100.0
  end

  def total_euros
    total_cents / 100.0
  end

  def pdf_exists?
    pdf_path.present? && File.exist?(pdf_path)
  end

  def xml_exists?
    xml_path.present? && File.exist?(xml_path)
  end

  def mark_sent!
    update!(status: 'sent', sent_at: Time.current)
  end

  def mark_peppol_sent!(guid)
    update!(status: 'peppol_sent', peppol_guid: guid, sent_at: Time.current)
  end

  def mark_failed!(reason = nil)
    update!(status: 'failed')
    Rails.logger.error("Invoice #{invoice_number} failed: #{reason}") if reason
  end

  def credit_note?
    invoice_type == 'credit_note'
  end

  # Generate the next credit note number: WWIZ-CN-2026-0001
  def self.next_credit_note_number(year: nil)
    year ||= Time.current.year
    prefix = "#{PREFIX}-CN-#{year}-"

    last = where('invoice_number LIKE ?', "#{prefix}%")
           .order(invoice_number: :desc)
           .pick(:invoice_number)

    seq = if last
            last.split('-').last.to_i + 1
          else
            1
          end

    "#{prefix}#{seq.to_s.rjust(4, '0')}"
  end

  # --- Octopus status helpers ---

  def octopus_synced?
    %w[synced peppol_sending peppol_sent peppol_delivered].include?(octopus_status)
  end

  def octopus_pending?
    octopus_status == 'pending'
  end

  def octopus_failed?
    octopus_status == 'failed'
  end

  def needs_octopus_sync?
    octopus_status.nil? && status == 'sent'
  end

  def octopus_status_label
    case octopus_status
    when nil then '-'
    when 'pending' then '⏳ Wachten'
    when 'synced' then '✅ Gesynchroniseerd'
    when 'peppol_sending' then '🔄 PEPPOL verzending...'
    when 'peppol_sent' then '🐙 PEPPOL verzonden'
    when 'peppol_delivered' then '📬 PEPPOL afgeleverd'
    when 'failed' then '❌ Mislukt'
    else octopus_status
    end
  end
end
