# frozen_string_literal: true

module LegalChatbot
  # An allowlisted, content-free record of what a provider request ACTUALLY
  # was, so ratings can be compared by real configuration rather than by what
  # a controller intended (RAT-003, plan section 6.4).
  #
  # Three rules govern this object:
  #
  # 1. ONLY named scalar fields. Messages, prompts, the question, the answer,
  #    case context, retrieved documents, credentials and endpoints have no
  #    accessor here and are dropped if passed. There is deliberately no
  #    method that takes a hash of arbitrary keys.
  # 2. NULL MEANS OMITTED. A nil temperature on a recorded trace means the
  #    provider request carried no temperature field - not "unknown". Unknown
  #    is the absence of a trace entirely (generation_trace_version null).
  # 3. The fingerprint covers CONFIGURATION only. Not performance, not usage,
  #    not rating, not language, not source, not user, not content. Two rows
  #    with the same fingerprint were generated by the same settings, which is
  #    what makes them comparable.
  class GenerationTrace
    SCHEMA_VERSION = 1

    PROVIDERS = %w[openai mistral bedrock].freeze
    REASONING_MODES = %w[none effort fixed_budget adaptive].freeze

    # Fields that may be recorded, in no particular order. Anything not named
    # here cannot enter the trace.
    REQUEST_FIELDS = %i[
      provider application_model provider_model
      reasoning_effort_requested reasoning_effort_used provider_reasoning_value
      reasoning_mode reasoning_token_budget
      temperature output_token_limit
      profile concise_mode follow_up
      prompt_version retrieval_version
    ].freeze

    # Fingerprint input order is FIXED (plan 6.4). Changing this order or its
    # membership changes every fingerprint, so it is a deliberate, versioned
    # act: bump SCHEMA_VERSION with it.
    FINGERPRINT_KEYS = %i[
      schema_version
      provider
      application_model
      provider_model
      reasoning_effort_requested
      reasoning_effort_used
      provider_reasoning_value
      reasoning_mode
      reasoning_token_budget
      temperature
      output_token_limit
      profile
      concise_mode
      prompt_version
      retrieval_version
    ].freeze

    PROVIDER_MODEL_LIMIT = 160
    # A public model revision: letters, digits, dot, dash, underscore, colon
    # for Bedrock inference profiles. Anything with a slash, whitespace, query
    # string or credential punctuation is not a model id.
    SAFE_PROVIDER_MODEL = /\A[A-Za-z0-9][A-Za-z0-9._:-]*\z/
    # Dots are legal in a model id (gpt-5.6-luna), so the charset alone lets a
    # hostname through. A public model revision never ends in a TLD.
    HOSTNAME_SUFFIX = /\.(com|net|org|io|ai|co|cloud|dev|local|internal)\z/i

    def initialize
      reset!
    end

    # Puma reuses threads and a corrective retry re-enters the same client, so
    # every provider call starts from empty. A trace must never describe an
    # earlier request.
    def reset!
      @data = {}
      @recorded = false
      self
    end

    def recorded?
      @recorded
    end

    # Called from a provider branch AFTER its request body is built, with
    # values read from that body.
    def record_request!(**fields)
      unknown = fields.keys - REQUEST_FIELDS
      raise ArgumentError, "GenerationTrace does not accept #{unknown.inspect}" if unknown.any?

      fields.each { |key, value| @data[key] = scalar(value) }
      @data[:provider] = normalize_provider(@data[:provider])
      @data[:reasoning_mode] = normalize_reasoning_mode(@data[:reasoning_mode])
      @recorded = true
      self
    end

    # Called after the provider responds, to upgrade the model revision and
    # add provider-reported reasoning usage. Never adds content.
    def record_response!(provider_model: nil, expected: nil, reasoning_tokens: nil)
      return self unless @recorded

      candidates = Array(expected).presence || [@data[:application_model], @data[:provider_model]].compact
      safe = self.class.safe_provider_model(provider_model,
                                            expected: candidates,
                                            fallback: @data[:application_model])
      @data[:provider_model] = safe if safe
      @data[:reasoning_tokens] = scalar(reasoning_tokens) if reasoning_tokens
      self
    end

    # An ALLOWLIST derived from the code-owned model configuration, not a
    # denylist of bad shapes (plan 6.4).
    #
    # A denylist cannot work here: "sk-secret-key-value" is structurally
    # identical to a model id, and so is an Azure deployment name. The only
    # reliable test is whether the provider returned something the application
    # actually invoked - the exact pinned id, or that id with a revision
    # suffix such as gpt-5.6-luna-2026-01-01. Anything else falls back to the
    # application's own model id, so an endpoint, a deployment name, a
    # credential or arbitrary provider text can never be persisted.
    def self.safe_provider_model(candidate, expected: nil, fallback: nil)
      text = candidate.to_s.strip
      return fallback if text.empty?
      return fallback if text.length > PROVIDER_MODEL_LIMIT
      return fallback unless SAFE_PROVIDER_MODEL.match?(text)
      return fallback if HOSTNAME_SUFFIX.match?(text)
      return fallback if azure_deployment_name?(text)

      known = Array(expected).map { |value| value.to_s.strip }.reject(&:empty?)
      return fallback if known.empty?
      return text if known.any? { |id| revision_of?(text, id) }

      fallback
    end

    # The same id, or that id followed by a revision separator.
    def self.revision_of?(text, id)
      return true if text == id

      %w[- . : _].any? { |separator| text.start_with?("#{id}#{separator}") }
    end

    def self.azure_deployment_name?(text)
      names = LegalChatbot::LlmClient::AZURE_DEPLOYMENT_NAMES.values
      names.include?(text)
    rescue NameError
      false
    end

    def to_h
      return {} unless @recorded

      @data.merge(schema_version: SCHEMA_VERSION).freeze
    end

    # SHA-256 over a canonical, fixed-order JSON array of the configuration
    # fields. Insertion order of record_request! cannot change it.
    def fingerprint
      return nil unless @recorded

      payload = FINGERPRINT_KEYS.map { |key| [key.to_s, fingerprint_value(key)] }
      Digest::SHA256.hexdigest(JSON.generate(payload))
    end

    # The subset written to chatbot_analytics. Column names, not trace names.
    def to_analytics_attributes
      return {} unless @recorded

      {
        provider_used: @data[:provider],
        provider_model_used: @data[:provider_model],
        reasoning_effort_requested: @data[:reasoning_effort_requested],
        reasoning_effort_used: @data[:reasoning_effort_used],
        provider_reasoning_value: @data[:provider_reasoning_value],
        reasoning_mode: @data[:reasoning_mode],
        reasoning_token_budget: @data[:reasoning_token_budget],
        reasoning_tokens: @data[:reasoning_tokens],
        profile_used: @data[:profile],
        concise_mode: @data[:concise_mode],
        temperature_used: @data[:temperature],
        output_token_limit: @data[:output_token_limit],
        follow_up: @data[:follow_up],
        prompt_version: @data[:prompt_version],
        retrieval_version: @data[:retrieval_version],
        generation_trace_version: SCHEMA_VERSION,
        generation_config_fingerprint: fingerprint
      }
    end

    private

    def fingerprint_value(key)
      return SCHEMA_VERSION if key == :schema_version

      @data[key]
    end

    # Only scalars survive. A hash or array here would mean someone tried to
    # put messages, a body or a document set into the trace.
    def scalar(value)
      case value
      when nil, true, false, Numeric then value
      when Symbol then value.to_s
      when String then value
      else nil
      end
    end

    def normalize_provider(value)
      text = value.to_s
      PROVIDERS.include?(text) ? text : nil
    end

    def normalize_reasoning_mode(value)
      text = value.to_s
      REASONING_MODES.include?(text) ? text : nil
    end
  end
end
